In [10]:
# Import pandas.
import pandas as pd

# Read the Excel file.
# Assign a variable.
# Use the pd.read_excel() function.
# Specify the name of the Excel file.
nc = pd.read_excel('national_categories.xlsx')

# Print the DataFrame.
nc

,appointment_date,icb_ons_code,sub_icb_location_name,service_setting,context_type,national_category,count_of_appointments,appointment_month
0,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Primary Care Network,Care Related Encounter,Patient contact during Care Home Round,3,2021-08
1,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Other,Care Related Encounter,Planned Clinics,7,2021-08
2,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Home Visit,79,2021-08
3,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,General Consultation Acute,725,2021-08
4,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Structured Medication Review,2,2021-08
...,...,...,...,...,...,...,...,...
817389,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Unplanned Clinical Activity,12,2022-06
817390,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Planned Clinics,4,2022-06
817391,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,Planned Clinical Procedure,92,2022-06
817392,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,General Consultation Routine,4,2022-06
817393,2022-06-30,E54000054,NHS West Yorkshire ICB - X2C4Y,Extended Access Provision,Care Related Encounter,General Consultation Acute,19,2022-06

In [11]:
# Read the CSV file.
# Assign a variable.
# Use the pd.read_csv() function.
# Specify the name of the CSV file.
ar = pd.read_csv('appointments_regional.csv')

# Print the DataFrame.
ar

,icb_ons_code,appointment_month,appointment_status,hcp_type,appointment_mode,time_between_book_and_appointment,count_of_appointments
0,E54000034,2020-01,Attended,GP,Face-to-Face,1 Day,8107
1,E54000034,2020-01,Attended,GP,Face-to-Face,15 to 21 Days,6791
2,E54000034,2020-01,Attended,GP,Face-to-Face,2 to 7 Days,20686
3,E54000034,2020-01,Attended,GP,Face-to-Face,22 to 28 Days,4268
4,E54000034,2020-01,Attended,GP,Face-to-Face,8 to 14 Days,11971
...,...,...,...,...,...,...,...
596816,E54000050,2022-06,Unknown,Unknown,Unknown,2 to 7 Days,21
596817,E54000050,2022-06,Unknown,Unknown,Unknown,22 to 28 Days,8
596818,E54000050,2022-06,Unknown,Unknown,Unknown,8 to 14 Days,28
596819,E54000050,2022-06,Unknown,Unknown,Unknown,More than 28 Days,17
596820,E54000050,2022-06,Unknown,Unknown,Unknown,Same Day,10

In [12]:
# Read the CSV file.
# Assign a variable.
# Use the pd.read_csv() function.
# Specify the name of the CSV file.
ad = pd.read_csv('actual_duration.csv')

# Print the DataFrame.
ad

,sub_icb_location_code,sub_icb_location_ons_code,sub_icb_location_name,icb_ons_code,region_ons_code,appointment_date,actual_duration,count_of_appointments
0,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,31-60 Minutes,364
1,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,21-30 Minutes,619
2,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,6-10 Minutes,1698
3,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,Unknown / Data Quality,1277
4,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,16-20 Minutes,730
...,...,...,...,...,...,...,...,...
137788,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,31-60 Minutes,430
137789,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,21-30 Minutes,751
137790,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,16-20 Minutes,921
137791,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,11-15 Minutes,1439
137792,X2C4Y,E38000254,NHS West Yorkshire ICB - X2C4Y,E54000054,E40000012,30-Jun-22,1-5 Minutes,1739

In [13]:
# Print the number of columns of each data set.
print(nc.columns)
print(ar.columns)
print(ad.columns)

Index(['appointment_date', 'icb_ons_code', 'sub_icb_location_name',
       'service_setting', 'context_type', 'national_category',
       'count_of_appointments', 'appointment_month'],
      dtype='object')
Index(['icb_ons_code', 'appointment_month', 'appointment_status', 'hcp_type',
       'appointment_mode', 'time_between_book_and_appointment',
       'count_of_appointments'],
      dtype='object')
Index(['sub_icb_location_code', 'sub_icb_location_ons_code',
       'sub_icb_location_name', 'icb_ons_code', 'region_ons_code',
       'appointment_date', 'actual_duration', 'count_of_appointments'],
      dtype='object')

In [18]:
# Determine shape of the national_category data set.
print(nc.shape)
print(nc.dtypes)

(817394, 8)
appointment_date         datetime64[ns]
icb_ons_code                     object
sub_icb_location_name            object
service_setting                  object
context_type                     object
national_category                object
count_of_appointments             int64
appointment_month                object
dtype: object

In [19]:
# Determine shape of the appointments regional data set.
print(ar.shape)
print(ar.dtypes)

(596821, 7)
icb_ons_code                         object
appointment_month                    object
appointment_status                   object
hcp_type                             object
appointment_mode                     object
time_between_book_and_appointment    object
count_of_appointments                 int64
dtype: object

In [20]:
# Determine shape of the actual_duration data set.
print(ad.shape)
print(ad.dtypes)

(137793, 8)
sub_icb_location_code        object
sub_icb_location_ons_code    object
sub_icb_location_name        object
icb_ons_code                 object
region_ons_code              object
appointment_date             object
actual_duration              object
count_of_appointments         int64
dtype: object

In [22]:
# Print the entire 'ad' DataFrame to perform a sense-check.
print(ad)

       sub_icb_location_code sub_icb_location_ons_code  \
0                        00L                 E38000130
1                        00L                 E38000130
2                        00L                 E38000130
3                        00L                 E38000130
4                        00L                 E38000130
...                      ...                       ...
137788                 X2C4Y                 E38000254
137789                 X2C4Y                 E38000254
137790                 X2C4Y                 E38000254
137791                 X2C4Y                 E38000254
137792                 X2C4Y                 E38000254

                             sub_icb_location_name icb_ons_code  \
0       NHS North East and North Cumbria ICB - 00L    E54000050
1       NHS North East and North Cumbria ICB - 00L    E54000050
2       NHS North East and North Cumbria ICB - 00L    E54000050
3       NHS North East and North Cumbria ICB - 00L    E54000050
4       NHS North East and North Cumbria ICB - 00L    E54000050
...                                            ...          ...
137788              NHS West Yorkshire ICB - X2C4Y    E54000054
137789              NHS West Yorkshire ICB - X2C4Y    E54000054
137790              NHS West Yorkshire ICB - X2C4Y    E54000054
137791              NHS West Yorkshire ICB - X2C4Y    E54000054
137792              NHS West Yorkshire ICB - X2C4Y    E54000054

       region_ons_code appointment_date         actual_duration  \
0            E40000012        01-Dec-21           31-60 Minutes
1            E40000012        01-Dec-21           21-30 Minutes
2            E40000012        01-Dec-21            6-10 Minutes
3            E40000012        01-Dec-21  Unknown / Data Quality
4            E40000012        01-Dec-21           16-20 Minutes
...                ...              ...                     ...
137788       E40000012        30-Jun-22           31-60 Minutes
137789       E40000012        30-Jun-22           21-30 Minutes
137790       E40000012        30-Jun-22           16-20 Minutes
137791       E40000012        30-Jun-22           11-15 Minutes
137792       E40000012        30-Jun-22             1-5 Minutes

        count_of_appointments
0                         364
1                         619
2                        1698
3                        1277
4                         730
...                       ...
137788                    430
137789                    751
137790                    921
137791                   1439
137792                   1739

[137793 rows x 8 columns]

In [25]:
# Print the entire 'nc' DataFrame to perform a sense-check.
print(nc)

       appointment_date icb_ons_code  \
0            2021-08-02    E54000050
1            2021-08-02    E54000050
2            2021-08-02    E54000050
3            2021-08-02    E54000050
4            2021-08-02    E54000050
...                 ...          ...
817389       2022-06-30    E54000054
817390       2022-06-30    E54000054
817391       2022-06-30    E54000054
817392       2022-06-30    E54000054
817393       2022-06-30    E54000054

                             sub_icb_location_name            service_setting  \
0       NHS North East and North Cumbria ICB - 00L       Primary Care Network
1       NHS North East and North Cumbria ICB - 00L                      Other
2       NHS North East and North Cumbria ICB - 00L           General Practice
3       NHS North East and North Cumbria ICB - 00L           General Practice
4       NHS North East and North Cumbria ICB - 00L           General Practice
...                                            ...                        ...
817389              NHS West Yorkshire ICB - X2C4Y  Extended Access Provision
817390              NHS West Yorkshire ICB - X2C4Y  Extended Access Provision
817391              NHS West Yorkshire ICB - X2C4Y  Extended Access Provision
817392              NHS West Yorkshire ICB - X2C4Y  Extended Access Provision
817393              NHS West Yorkshire ICB - X2C4Y  Extended Access Provision

                  context_type                       national_category  \
0       Care Related Encounter  Patient contact during Care Home Round
1       Care Related Encounter                         Planned Clinics
2       Care Related Encounter                              Home Visit
3       Care Related Encounter              General Consultation Acute
4       Care Related Encounter            Structured Medication Review
...                        ...                                     ...
817389  Care Related Encounter             Unplanned Clinical Activity
817390  Care Related Encounter                         Planned Clinics
817391  Care Related Encounter              Planned Clinical Procedure
817392  Care Related Encounter            General Consultation Routine
817393  Care Related Encounter              General Consultation Acute

        count_of_appointments appointment_month
0                           3           2021-08
1                           7           2021-08
2                          79           2021-08
3                         725           2021-08
4                           2           2021-08
...                       ...               ...
817389                     12           2022-06
817390                      4           2022-06
817391                     92           2022-06
817392                      4           2022-06
817393                     19           2022-06

[817394 rows x 8 columns]

In [26]:
# Print the entire 'ar' DataFrame to perform a sense-check.
print(ar)

       icb_ons_code appointment_month appointment_status hcp_type  \
0         E54000034           2020-01           Attended       GP
1         E54000034           2020-01           Attended       GP
2         E54000034           2020-01           Attended       GP
3         E54000034           2020-01           Attended       GP
4         E54000034           2020-01           Attended       GP
...             ...               ...                ...      ...
596816    E54000050           2022-06            Unknown  Unknown
596817    E54000050           2022-06            Unknown  Unknown
596818    E54000050           2022-06            Unknown  Unknown
596819    E54000050           2022-06            Unknown  Unknown
596820    E54000050           2022-06            Unknown  Unknown

       appointment_mode time_between_book_and_appointment  \
0          Face-to-Face                             1 Day
1          Face-to-Face                    15  to 21 Days
2          Face-to-Face                       2 to 7 Days
3          Face-to-Face                    22  to 28 Days
4          Face-to-Face                     8  to 14 Days
...                 ...                               ...
596816          Unknown                       2 to 7 Days
596817          Unknown                    22  to 28 Days
596818          Unknown                     8  to 14 Days
596819          Unknown                 More than 28 Days
596820          Unknown                          Same Day

        count_of_appointments
0                        8107
1                        6791
2                       20686
3                        4268
4                       11971
...                       ...
596816                     21
596817                      8
596818                     28
596819                     17
596820                     10

[596821 rows x 7 columns]

In [37]:
# Identify the number of missing values in the 'nc' data set.
nc = pd.read_excel('national_categories.xlsx')
nc.head()

,appointment_date,icb_ons_code,sub_icb_location_name,service_setting,context_type,national_category,count_of_appointments,appointment_month
0,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Primary Care Network,Care Related Encounter,Patient contact during Care Home Round,3,2021-08
1,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,Other,Care Related Encounter,Planned Clinics,7,2021-08
2,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Home Visit,79,2021-08
3,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,General Consultation Acute,725,2021-08
4,2021-08-02,E54000050,NHS North East and North Cumbria ICB - 00L,General Practice,Care Related Encounter,Structured Medication Review,2,2021-08

In [41]:
nc_na = nc[nc.isna().any(axis=1)]
nc_na.shape

(0, 8)

In [42]:
# Identify the number of missing values in the 'ad' data set.
ad = pd.read_csv('actual_duration.csv')
ad.head()

,sub_icb_location_code,sub_icb_location_ons_code,sub_icb_location_name,icb_ons_code,region_ons_code,appointment_date,actual_duration,count_of_appointments
0,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,31-60 Minutes,364
1,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,21-30 Minutes,619
2,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,6-10 Minutes,1698
3,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,Unknown / Data Quality,1277
4,00L,E38000130,NHS North East and North Cumbria ICB - 00L,E54000050,E40000012,01-Dec-21,16-20 Minutes,730

In [43]:
ad_na = ad[ad.isna().any(axis=1)]
ad_na.shape

(0, 8)

In [44]:
# Identify the number of missing values in the 'ar' data set.
ar = pd.read_csv('appointments_regional.csv')
ar.head()

,icb_ons_code,appointment_month,appointment_status,hcp_type,appointment_mode,time_between_book_and_appointment,count_of_appointments
0,E54000034,2020-01,Attended,GP,Face-to-Face,1 Day,8107
1,E54000034,2020-01,Attended,GP,Face-to-Face,15 to 21 Days,6791
2,E54000034,2020-01,Attended,GP,Face-to-Face,2 to 7 Days,20686
3,E54000034,2020-01,Attended,GP,Face-to-Face,22 to 28 Days,4268
4,E54000034,2020-01,Attended,GP,Face-to-Face,8 to 14 Days,11971

In [45]:
ar_na = ar[ar.isna().any(axis=1)]
ar_na.shape

(0, 7)